# DB 설정
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: ${sql-local-server-password}
        url: jdbc:mysql://board.cjpejm6zlwuk.ap-northeast-2.rds.amazonaws.com:3306/board
        username: admin
upload:
    path: /apps/board/dev/
    
sql-server-password: ${SQL_PASSWORD}

domain:
    name : localhost:8080
    alarm : localhost:8081

logging:
    level:
        com:
            zaxxer:
                hikari: INFO
        javax:
            sql:
                DataSource: OFF
        jdbc:
            audit: OFF
            resultset: OFF
            resultsettable: INFO  #SQL 결과 데이터 Table을 로그로 남긴다.
            sqlonly: OFF     #SQL만 로그로 남긴다.
            sqltiming: INFO    #SQL과 소요시간을 표기한다.
            connection : OFF  # 커넥션 확인가능
        org:
            hibernate:
                SQL: DEBUG
                type:
                    descriptor:
                        sql:
                            BasicBinder: TRACE