# myBatis
mybatis:
    mapper-locations: mybatis/mapper/*.xml
    type-aliases-package: com.hoin.boardStudy
    config-location: classpath:mybatis-config.xml
    
## 파일 크기 설정
spring:
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 50MB
    mail:
        host: smtp.gmail.com
        port: 587
        username: dahoonemailtest@gmail.com
        password: andrprnfma
        properties:
          mail:
              smtp:
                  auth: true
                  starttls:
                      enable: true



logging:
    ##    config: classpath:log/logback-${spring.profiles}.xml
    config: classpath:log/logback.xml

