# DB 설정
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: ${sql-local-server-password}
        url: jdbc:mysql://board.cjpejm6zlwuk.ap-northeast-2.rds.amazonaws.com:3306/board
        username: admin
# thymeleaf (tomcat 재시동 없이 변경 사항 반영하기)
    thymeleaf:
        cache: false
        prefix: file:src/main/resources/templates/

upload:
    path: C:/upload/
    
sql-local-server-password: ${SQL_PASSWORD}

domain:
    name : localhost:8080
    alarm : localhost:8081