# myBatis
mybatis:
    mapper-locations: mybatis/mapper/*.xml
    type-aliases-package: com.hoin.boardStudy
    config-location: classpath:mybatis-config.xml

logging:
    ##    config: classpath:log/logback-${spring.profiles}.xml
    config: classpath:log/logback.xml
