# myBatis
mybatis:
    mapper-locations: mybatis/mapper/*.xml
    type-aliases-package: com.hoin.boardStudy
    config-location: classpath:mybatis-config.xml


    
# 파일 크기 설정
spring:
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 50MB
    mail:
        host: smtp.gmail.com
        port: 587
        username: alarmmanager714@gmail.com
        password: ${gmail_password}
        properties:
          mail:
              transport:
                  protocol: smtp
              smtp:
                  ssl:
                      protocols: TLSv1.2
                  auth: true
                  starttls:
                      enable: true
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher

# redis 설정
    session:
      storage-type: redis
    redis:
      host: localhost
      port: 6379