# DB 설정
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: ${sql-server-password}
        url: jdbc:mysql://dev.donghyeon.dev:3308/board
        username: root
upload:
    path: /apps/board/real/
    
sql-server-password: ${SQL_PASSWORD}

domain:
    name : board.donghyeon.dev